### ISSUE TITLE
Run as "bacteria"

### ISSUE THREAD

**Issue by patrickmslatteryvt** [blippar/git2etcd#11]
Is there a way to run this as a "[bacteria](http://www.slideshare.net/ToriWieldt/from-pets-to-cattle-to-bacteria-oscon-bof)" process?
In other words rather than continuously polling the repo it would be called by a Git post-receive hook instead and would then sync down from the Git repo and up to etcd just once and exit.

**Comment by patrickmslatteryvt** [comment]
Temporary workaround:

```
timeout 15 \
  docker run \
    -it \
    --rm \
    --env="G2E_REPO_URL=http://git.mydomain.com/config_files.git" \
    --env="G2E_ETCD_HOSTS=http://etcd.mydomain.com:2379" \
    --hostname="git2etcd" \
    --memory="32M" \
    --name="git2etcd" \
    blippar/git2etcd:latest
docker kill git2etcd
docker rm git2etcd
```

**Comment by Dal-Papa** [comment]
@patrickmslatteryvt : Apologies for the response delay, somehow the notification didn't make it. I believe we implemented a Git push hook in there which, if you make your GitHub repo point to your git2etcd service, is able to pick that up. Then you can have the `repo.synccycle` config to 0 to never sync automatically. 
Let me know if that helps.

**Comment by Dal-Papa** [comment]
Closing issue as it should have been implemented already and no feedback from user.
