### ISSUE TITLE
Problems with syncing to etcd

### ISSUE THREAD

**Issue by patrickmslatteryvt** [blippar/git2etcd#9]
I'm having some problems getting git2etcd to sync a test repo to an Etcd server. Here's what I have:

```
docker pull blippar/git2etcd

docker run \
  -it \
  --rm \
  --hostname="git2etcd" \
  --memory="512M" \
  --name="git2etcd" \
  blippar/git2etcd:latest sh

mkdir -p /data/repo

cat > /app/git2etcd.json <<EOF
{
  "host": {
    "listen": "",
    "port": "4242",
    "hook": "hook"
  },
  "repo": {
    "url": "https://github.com/0rax/fishline.git",
    "path": "/data/repo",
    "synccycle": "30"
  },
  "etcd": {
    "hosts": [
      "http://etcd.dev.mydomain.com:2379"
    ]
  }
}
EOF

/usr/local/sbin/gosu app /app/git2etcd -config /app/git2etcd.json
```

This gives me the following error message:

```
WARN[0000] Couldn't sync repo                            error=Couldn't lookup ref: The given reference name 'refs/remotes/origin/' is not valid
WARN[0030] Couldn't sync automatically                   error=Couldn't lookup ref: The given reference name 'refs/remotes/origin/' is not valid
```

The directory /data/repo/ is being automatically populated with the cloned Git repo but nothing is getting pushed to Etcd. I verified that I can push to etcd from inside the container with the following:

```
# Write to Etcd
curl -L http://etcd.dev.mydomain.com:2379/v2/keys/app/git2etcd.json -XPUT --data-urlencode value@/app/git2etcd.json

# Read it back (from another system)
curl -sL http://etcd.dev.mydomain.com:2379/v2/keys/app/git2etcd.json | jq .
{
  "action": "get",
  "node": {
    "key": "/app/git2etcd.json",
    "value": "{\n  \"host\": {\n    \"listen\": \"\",\n    \"port\": \"4242\",\n    \"hook\": \"hook\"\n  },\n  \"repo\": {\n    \"url\": \"https://github.com/0rax/fishline.git\",\n    \"path\": \"/data/repo\",\n    \"synccycle\": \"30\"\n  },\n  \"etcd\": {\n    \"hosts\": [\n      \"http://etcd.dev.brandcloud.mywebgrocer.com:2379\"\n    ]\n  }\n}\n",
    "modifiedIndex": 6,
    "createdIndex": 6
  }
}
```

Any ideas on what I can try next?
Thanks

**Comment by 0rax** [comment]
Thanks for your report, this is due to the lack of branch in the configuration file.

When the branch is ommited, our software tries to querry `refs/remotes/origin/` instead of `refs/remotes/origin/master` (the default value for `repo.branch` seems to be ignored).

This will be fixed in the next release and we will add the branch parameter to the `README.md` as it seems to have been omited at first.

Sorry for the inconvenience, in order to fix your test you just need to update the repo section in order to add a `branch` parameter.

``` json
  "repo": {
    "url": "https://github.com/0rax/fishline.git",
    "branch": "master",
    "path": "/data/repo",
    "synccycle": "30"
  },
```

**Comment by patrickmslatteryvt** [comment]
That did the trick, it works as expected now.
Thanks!

**Comment by 0rax** [comment]
Glad you checked our software, thanks again for the report it was really helpful !
